#!/bin/sh

case $1 in
    pre) /usr/bin/throttle performance ;;
    post)
        if </sys/class/power_supply/AC/online grep 0 > /dev/null 2>&1; then
            /usr/bin/throttle powersave
        else
    		/usr/bin/throttle performance
        fi
    ;;
esac
exit 0
